apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-website
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - image: duckiedo/composetest:v4
          name: ecom-web
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: DB_HOST
              value: "mariadb-service.default.svc.cluster.local" 
            - name: DB_PORT
              value: "3306"  
            - name: DB_NAME
              value: "ecomdb"  
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: DB_PASSWORD
            - name: FEATURE_DARK_MODE
              valueFrom:
                configMapKeyRef:
                  name: darkmode-config
                  key: FEATURE_DARK_MODE
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: default
spec:
  selector:
    app: ecommerce
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ecommerce-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecommerce-website
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
