apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: default
data:
  my-custom.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    max_connections = 200
    sql_mode = STRICT_TRANS_TABLES
